# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Instalação

Para instalar o NumPy, você pode usar o pip, que é o gerenciador de pacotes do Python.

```python
pip install numpy
```

## Arrays

Um array é uma estrutura de dados que armazena valores do mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes. Vamos criar um array.



In [1]:
import numpy as np

#criar um array
array = np.array([1,2,3,4,5])

print(array)

[1 2 3 4 5]


conhecendo um array e indexaçao e slicing

In [4]:
print (array[0]) #pega meu array e busca nele o valor que esta associado ao indice 0 que seria 1
#python comeca a contar do 1

print(array[1:4]) #slicing - pegar uma parte do array, o primeiro numero é excluso
#do indice 1 ate o indice 4

print(array[0:-1])# o ultimo é excluso, do indice 0 (primeiro) até o ultimo

print(array[0:-1:2])#step = passo -> ele pula e vai de 2 em 2

print(array[0::2])#entre os dois pontos nao passei nada - incluiu o ultimo

print(array[::2])#pegando desde o inicio - considera desde o inicio

print(array[::])#pega desde o inicio -> ate o final

print(array[::-1]) #contou de tras para frente

# o segundo ponto é o step ou seja o passo

1
[2 3 4]
[1 2 3 4]
[1 3]
[1 3 5]
[1 3 5]
[1 2 3 4 5]
[5 4 3 2 1]
